### ISSUE TITLE
Long-term Feature Requests

### ISSUE THREAD

**Issue by JasonYao** [JasonYao/DEPRECATED-dotfiles#8]
## Completed
- [Unix] Separate out server hardening into own repo
  - Completed, new security hardening repo is located [here](https://github.com/JasonYao/server-setup)

## TODO
- [OSX] Homebrew
  - [x] Hide brew installation
  - [ ] Leave only progress bars

- [OSX] add to the sidebar:
  - [ ] Home directory
  - [ ] macOS volume
  - [ ] Projects directory
  - [ ] Torrents directory
  - [ ] current NYU semester folder
  - NOTES:
    - [ ] Maybe possible via com.apple.Finder or com.apple.sidebarlists
    - As of [OSX 10.11](http://lists.apple.com/archives/cocoa-dev/2015/Dec/msg00102.html), API used to add a folder programmatically to finder's favourites is deprecated. Unknown what the new API is.
    - Doesn't seem to be a valid osascript usage
    - Can't use `com.apple.finder` nor `com.apple.sidebarlists`, since .finder keeps a list of `ALL` drives that've been opened before, and appears to be using actual x- and y-positions. This means insertion/deletion of folders does not appear possible programmatically in a non-fugly way.
